export {default as SignCreateAccScreen} from './authScreens/SignCreateAccScreen';
export {default as LogInScreen} from './authScreens/LogInScreen';
export {default as SignUpScreen} from './authScreens/SignUpScreen';
export {default as SearchScreen} from './searchScreens/SearchScreen';
export {default as HomeScreen} from './HomeScreens/HomeScreen';
export {default as SectionScreen} from './HomeScreens/SectionScreen';
export {default as TrailersScreen} from './HomeScreens/TrailersScreen';
export {default as MovieScreen} from './HomeScreens/MovieScreen';
export {default as TimeLineScreen} from './HomeScreens/TimeLineScreen';
